apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vector-store-manager-server.fullname" . }}
  labels:
    {{- include "vector-store-manager-server.labels" . | nindent 4 }}
data:
  config.yaml: |
    httpPort: {{ .Values.httpPort }}
    grpcPort: {{ .Values.grpcPort }}
    auth:
      enable: {{ .Values.global.auth.enable }}
      rbacInternalServerAddr: {{ .Values.global.auth.rbacInternalServerAddr }}
