apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vector-store-manager-server.fullname" . }}
  labels:
    {{- include "vector-store-manager-server.labels" . | nindent 4 }}
data:
  config.yaml: |
    httpPort: {{ .Values.httpPort }}
    grpcPort: {{ .Values.grpcPort }}
    internalGrpcPort: {{ .Values.internalGrpcPort }}
    fileManagerServerAddr: {{ .Values.fileManagerServerAddr }}
    fileManagerServerInternalAddr: {{ .Values.fileManagerServerInternalAddr }}
    llmEngineAddr: {{ .Values.llmEngineAddr }}
    llmEngine: {{ .Values.llmEngine }}
    model: {{ .Values.model }}
    database:
      host: {{ .Values.global.database.host }}
      port: {{ .Values.global.database.port }}
      database: {{ .Values.database.database }}
      username: {{ .Values.global.database.username }}
      passwordEnvName: DB_PASSWORD
    vectorDatabase:
      host: {{ .Values.vectorDatabase.host }}
      port: {{ .Values.vectorDatabase.port }}
      database: {{ .Values.vectorDatabase.database }}
      username: {{ .Values.vectorDatabase.username }}
      passwordEnvName: VECTOR_DB_PASSWORD
    objectStore:
      s3:
        endpointUrl: {{ .Values.global.objectStore.s3.endpointUrl }}
        region: {{ .Values.global.objectStore.s3.region }}
        bucket: {{ .Values.global.objectStore.s3.bucket }}
    auth:
      enable: {{ .Values.global.auth.enable }}
      rbacInternalServerAddr: {{ .Values.global.auth.rbacInternalServerAddr }}
