{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "vector-store-manager-server.serviceAccountName" . }}
  labels:
    {{- include "vector-store-manager-server.labels" . | nindent 4 }}
{{- end -}}
