global:
  database:
    host:
    port:
    username:
  databaseSecret:
    name:
    key:
  objectStore:
    s3:
      endpointUrl:
      region:
      bucket:
  awsSecret:
    name:
    accessKeyIdKey:
    secretAccessKeyKey:
  ingress:
    ingressClassName:
    annotations:
    tls:
      hosts:
      secretName:

  auth:
    enable:
    rbacInternalServerAddr:

httpPort: 8080
grpcPort: 8081
internalGrpcPort: 8083

# The following default values work if the services run in the same namespace.
fileManagerServerAddr: file-manager-server-grpc:8081
fileManagerServerInternalAddr: file-manager-server-internal-grpc:8083
ollamaServerAddr: inference-manager-engine-ollama:8080

model: all-minilm

replicaCount: 1
image:
  repository: public.ecr.aws/v8n3t7y5/llm-operator/vector-store-manager-server
  pullPolicy: IfNotPresent

version:

database:
  database: vector_store_manager

vectorDatabase:
  host: milvus.milvus
  port: 19530
  username: root
  database: default
vectorDatabaseSecret:
  name: vector-store
  key: password
