global:
  database:
    host:
    port:
    username:
    ssl:
      mode:
      rootCert:
    createDatabase:
    originalDatabase:

  databaseSecret:
    name:
    key:
  objectStore:
    s3:
      endpointUrl:
      region:
      bucket:
      assumeRole:
        roleArn:
        externalId:
  awsSecret:
    name:
    accessKeyIdKey:
    secretAccessKeyKey:
  ingress:
    ingressClassName:
    annotations:
    tls:
      hosts:
      secretName:

  auth:
    enable:
    rbacInternalServerAddr:

httpPort: 8080
grpcPort: 8081
internalGrpcPort: 8083

# The following default values work if the services run in the same namespace.
fileManagerServerAddr: file-manager-server-grpc:8081
fileManagerServerInternalAddr: file-manager-server-internal-grpc:8083
llmEngineAddr: inference-manager-engine-llm:8080
llmEngine: ollama

model: all-minilm

replicaCount: 1

serviceAccount:
  create: true

image:
  repository: public.ecr.aws/cloudnatix/llmariner/vector-store-manager-server
  pullPolicy: IfNotPresent

podAnnotations:
nodeSelector:
affinity:
tolerations:

version:

database:
  database: vector_store_manager

vectorDatabase:
  host: milvus.milvus
  port: 19530
  username: root
  database: default
  ssl:
    mode: disable

vectorDatabaseSecret:
  name: vector-store
  key: password

resources:
  requests:
    cpu: "250m"
    memory: "500Mi"
  limits:
    cpu: "250m"

livenessProbe:
  httpGet:
    path: /healthz
    port: http
    scheme: HTTP
  initialDelaySeconds: 3
  failureThreshold: 5
  timeoutSeconds: 3

podSecurityContext:
  fsGroup: 2000
securityContext:
  readOnlyRootFilesystem: true
  capabilities:
    drop:
    - ALL
  runAsNonRoot: true
  runAsUser: 1000
